// transpile-browser-modules.ts — single-source the pure logic modules to the
// browser (eng-review D1 = A).
//
// router.ts / venue-entry.ts / id-gen.ts are pure, zero-`node:` modules used by
// the CLI ingest path. The in-app edit-mode (②-A) needs the EXACT same logic in
// the browser. Instead of hand-mirroring (which can only parity-check keyword
// DATA, not matchKeyword word-boundary / tie-rank LOGIC), we transpile the TS
// source to a browser ESM at scaffold time — same pattern as regenerate-sw.ts
// generating sw.js. One source, two runtimes, zero drift class.
//
// Bun.Transpiler strips types only (no bundling, no minify) → the emitted JS is
// the same code the CLI runs, just type-erased. The modules export named symbols
// the browser imports directly (no default export, no CommonJS).
//
// A6 (regenerate-sw classifier): the SW js-classifier matches single-level
// js/*.js ONLY. These MUST land flat in js/ (not js/lib/), or the next ingest's
// regenerate-sw hard-errors on an unclassified file. transpileBrowserModules
// writes flat into <jsDir>; callers pass the trip's js/ dir.

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Source .ts (in skills/_lib) → emitted .js basename (in the trip's js/).
// Order is irrelevant — each is an independent ESM. Keep them flat.
export const BROWSER_MODULES: { src: string; out: string }[] = [
  { src: 'router.ts',       out: 'router.js' },
  { src: 'venue-entry.ts',  out: 'venue-entry.js' },
  { src: 'id-gen.ts',       out: 'id-gen.js' },
];

const HEADER =
  '// GENERATED by skills/_lib/transpile-browser-modules.ts from the matching\n' +
  '// .ts in skills/_lib — DO NOT EDIT. Edit the .ts source + re-run the\n' +
  '// transpile (any scaffold/ingest does it). Single-source: the CLI runs the\n' +
  '// .ts, the browser runs this type-erased mirror (eng-review D1).\n';

// Transpile every browser module from skills/_lib into <jsDir>. Returns the list
// of emitted basenames. Throws if a module accidentally carries a `node:` import
// (it would 404 in the browser) — fail loud at build, not silently at runtime.
export async function transpileBrowserModules(jsDir: string): Promise<string[]> {
  const libDir = fileURLToPath(new URL('.', import.meta.url));
  const transpiler = new Bun.Transpiler({ loader: 'ts', target: 'browser' });
  const emitted: string[] = [];
  for (const m of BROWSER_MODULES) {
    const tsSrc = await readFile(join(libDir, m.src), 'utf8');
    if (/from\s+['"]node:/.test(tsSrc) || /\brequire\s*\(/.test(tsSrc)) {
      throw new Error(`transpile-browser-modules: ${m.src} has a node builtin import — not browser-safe`);
    }
    const js = await transpiler.transform(tsSrc);
    await writeFile(join(jsDir, m.out), HEADER + js);
    emitted.push(m.out);
  }
  return emitted;
}
