import { test, expect } from 'bun:test';
import { mkdtemp, rm, readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { BROWSER_MODULES, transpileBrowserModules } from './transpile-browser-modules';

// D1 = A: single-source the pure logic modules to the browser via transpile.
// These tests pin the contract Lane C depends on.

test('BROWSER_MODULES includes id-gen so scaffold emits js/id-gen.js (eng A5/T9)', () => {
  const outs = BROWSER_MODULES.map((m) => m.out);
  expect(outs).toContain('id-gen.js');
  expect(outs).toContain('router.js');
  expect(outs).toContain('venue-entry.js');
});

test('every emitted module is FLAT in js/ (no subdir) — SW classifier matches js/*.js only (A6)', () => {
  for (const m of BROWSER_MODULES) {
    expect(m.out).not.toContain('/');     // no js/lib/foo.js — would hard-error regenerate-sw
    expect(m.out.endsWith('.js')).toBe(true);
  }
});

test('transpiles each .ts → a type-erased browser ESM with its named exports', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'transpile-'));
  try {
    const emitted = await transpileBrowserModules(dir);
    expect(emitted.sort()).toEqual(['id-gen.js', 'router.js', 'venue-entry.js']);
    const files = (await readdir(dir)).sort();
    expect(files).toEqual(['id-gen.js', 'router.js', 'venue-entry.js']);

    const router = await readFile(join(dir, 'router.js'), 'utf8');
    expect(router).toMatch(/export function route\(/);
    expect(router).toMatch(/export const MIN_CONFIDENCE/);
    expect(router).toMatch(/export const TIE_THRESHOLD/);
    expect(router).not.toMatch(/:\s*RouteResult/);     // types stripped
    expect(router).not.toMatch(/interface /);

    const venue = await readFile(join(dir, 'venue-entry.js'), 'utf8');
    expect(venue).toMatch(/export function buildVenueEntry\(/);
    expect(venue).not.toMatch(/interface VenueFields/);

    const idgen = await readFile(join(dir, 'id-gen.js'), 'utf8');
    expect(idgen).toMatch(/export function slug\(/);
    expect(idgen).toMatch(/export function uniqueId\(/);

    // Every emitted module carries the DO-NOT-EDIT header + no node import.
    for (const f of files) {
      const src = await readFile(join(dir, f), 'utf8');
      expect(src).toMatch(/GENERATED by skills\/_lib\/transpile-browser-modules/);
      expect(src).not.toMatch(/from\s+['"]node:/);
    }
  } finally { await rm(dir, { recursive: true, force: true }); }
});

test('the committed templates/js mirrors are in sync with the .ts source', async () => {
  // The repo commits the transpiled mirrors so the template e2e (served from
  // templates/) and the parity tests see them without a build step. Re-transpile
  // and assert byte-equality — a stale commit fails here (run the scaffold or
  // re-transpile to refresh).
  const dir = await mkdtemp(join(tmpdir(), 'transpile-sync-'));
  try {
    await transpileBrowserModules(dir);
    const tplDir = join(import.meta.dir, '../../templates/js');
    for (const m of BROWSER_MODULES) {
      const fresh = await readFile(join(dir, m.out), 'utf8');
      const committed = await readFile(join(tplDir, m.out), 'utf8');
      expect(committed).toBe(fresh);
    }
  } finally { await rm(dir, { recursive: true, force: true }); }
});
