// GENERATED by skills/_lib/transpile-browser-modules.ts from the matching
// .ts in skills/_lib — DO NOT EDIT. Edit the .ts source + re-run the
// transpile (any scaffold/ingest does it). Single-source: the CLI runs the
// .ts, the browser runs this type-erased mirror (eng-review D1).
export function slug(s) {
  const ascii = s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  if (ascii.length >= 3)
    return ascii.slice(0, 40);
  let h = 0;
  for (const ch of s)
    h = h * 31 + ch.charCodeAt(0) >>> 0;
  return "venue-" + h.toString(36);
}
export function uniqueId(base, taken) {
  if (!taken.has(base))
    return base;
  for (let n = 2;; n++) {
    const c = `${base}-${n}`;
    if (!taken.has(c))
      return c;
  }
}
