// GENERATED by skills/_lib/transpile-browser-modules.ts from the matching
// .ts in skills/_lib — DO NOT EDIT. Edit the .ts source + re-run the
// transpile (any scaffold/ingest does it). Single-source: the CLI runs the
// .ts, the browser runs this type-erased mirror (eng-review D1).
export const TIE_THRESHOLD = 0.1;
export const MIN_CONFIDENCE = 0.4;
const DESSERTS_KEYWORDS = [
  "甜點",
  "甜品",
  "蛋糕",
  "ケーキ",
  "カフェ",
  "cafe",
  "café",
  "coffee",
  "dessert",
  "sweets",
  "parfait",
  "パフェ",
  "マリトッツォ",
  "maritozzo",
  "鯛魚燒",
  "たい焼き",
  "可麗餅",
  "クレープ",
  "crepe",
  "ice cream",
  "gelato",
  "soft cream",
  "ソフトクリーム",
  "puff",
  "tart",
  "tarte",
  "和菓子",
  "wagashi",
  "annin",
  "杏仁豆腐",
  "蛋撻",
  "egg tart",
  "楊枝甘露",
  "燉奶",
  "雙皮奶",
  "西多士",
  "豆花",
  "芋圓",
  "珍珠奶茶",
  "bubble tea",
  "boba",
  "剉冰",
  "挫冰",
  "雪花冰",
  "shaved ice",
  "빙수",
  "bingsu",
  "호떡",
  "hotteok",
  "糖水",
  "甜湯",
  "車輪餅",
  "카페",
  "디저트",
  "dessert",
  "케이크",
  "커피",
  "빵집",
  "베이커리",
  "마카롱",
  "크로플"
];
const FANDOM_KEYWORDS = [
  "pokemon",
  "ポケモン",
  "寶可夢",
  "皮卡丘",
  "ピカチュウ",
  "pikachu",
  "sanrio",
  "サンリオ",
  "三麗鷗",
  "布丁狗",
  "pompompurin",
  "ポムポムプリン",
  "美樂蒂",
  "my melody",
  "マイメロディ",
  "sailor moon",
  "セーラームーン",
  "美少女戰士",
  "月亮",
  "precure",
  "プリキュア",
  "光美",
  "光之美少女",
  "cardcaptor sakura",
  "カードキャプターさくら",
  "庫洛魔法使",
  "庫洛",
  "クロウカード",
  "clamp",
  "kuromi",
  "クロミ",
  "庫洛米",
  "hello kitty",
  "ハローキティ",
  "凱蒂貓"
];
const FOOD_KEYWORDS = [
  "拉麵",
  "ラーメン",
  "ramen",
  "sushi",
  "寿司",
  "壽司",
  "焼肉",
  "燒肉",
  "yakiniku",
  "izakaya",
  "居酒屋",
  "レストラン",
  "restaurant",
  "tempura",
  "天ぷら",
  "天婦羅",
  "うどん",
  "udon",
  "soba",
  "そば",
  "蕎麥",
  "donburi",
  "丼",
  "牛丼",
  "鰻",
  "鰻魚",
  "うなぎ",
  "味噌汁",
  "miso soup",
  "miso",
  "弁当",
  "お弁当",
  "定食",
  "食堂",
  "燒臘",
  "叉燒",
  "燒鵝",
  "點心",
  "dim sum",
  "飲茶",
  "一盅兩件",
  "茶餐廳",
  "車仔麵",
  "雲吞麵",
  "菠蘿包",
  "絲襪奶茶",
  "打邊爐",
  "火鍋",
  "hotpot",
  "煲仔飯",
  "腸粉",
  "魚蛋",
  "燒味",
  "滷肉飯",
  "魯肉飯",
  "牛肉麵",
  "小籠包",
  "雞排",
  "鹽酥雞",
  "蚵仔煎",
  "臭豆腐",
  "割包",
  "刈包",
  "擔仔麵",
  "김치",
  "kimchi",
  "불고기",
  "bulgogi",
  "비빔밥",
  "bibimbap",
  "삼겹살",
  "samgyeopsal",
  "떡볶이",
  "tteokbokki",
  "치킨",
  "korean fried chicken",
  "냉면",
  "naengmyeon",
  "korean bbq",
  "韓式",
  "김밥",
  "gimbap",
  "kimbap",
  "라멘",
  "맛집",
  "먹방",
  "mukbang",
  "분식",
  "포차",
  "포장마차",
  "국밥",
  "칼국수",
  "순대",
  "족발",
  "보쌈",
  "곱창",
  "감자탕",
  "한식",
  "海南雞飯",
  "hainanese chicken",
  "肉骨茶",
  "bak kut teh",
  "laksa",
  "叻沙",
  "pad thai",
  "ผัดไทย",
  "泰式",
  "ต้มยำ",
  "tom yum",
  "冬蔭功",
  "pho",
  "phở",
  "河粉",
  "bánh mì",
  "satay",
  "沙嗲",
  "nasi lemak"
];
const NEARBY_KEYWORDS = [
  "駅",
  "車站",
  "神社",
  "shrine",
  "寺",
  "temple",
  "park",
  "公園",
  "展望",
  "observatory",
  "skytree",
  "晴空塔",
  "夜景",
  "スーパー",
  "supermarket",
  "コンビニ",
  "convenience store",
  "ドラッグストア",
  "drugstore",
  "薬局",
  "pharmacy",
  "商店街",
  "shopping street",
  "港鐵",
  "mtr",
  "捷運",
  "mrt",
  "地鐵",
  "지하철",
  "街市",
  "市場",
  "市集",
  "夜市",
  "night market",
  "시장",
  "skytrain",
  "廟",
  "寺廟",
  "教堂",
  "cathedral"
];
const ATTRACTION_KEYWORDS = [
  "museum",
  "美術館",
  "ミュージアム",
  "博物館",
  "体験館",
  "体験",
  "體驗",
  "期間限定",
  "ポップアップ",
  "pop-up",
  "popup",
  "フォトスポット",
  "photo spot",
  "写真映え",
  "インスタ映え",
  "instagrammable",
  "テーマパーク",
  "theme park",
  "アトラクション",
  "attraction",
  "限定オープン",
  "デジタルアート",
  "digital art",
  "プラネタリウム",
  "planetarium",
  "観景台",
  "観景",
  "展望台",
  "rooftop",
  "sky deck",
  "オープン",
  "新スポット"
];
const PRIORITY = ["attractions", "desserts", "fandom", "food", "nearby"];
const KEYWORDS = {
  attractions: ATTRACTION_KEYWORDS,
  desserts: DESSERTS_KEYWORDS,
  fandom: FANDOM_KEYWORDS,
  food: FOOD_KEYWORDS,
  nearby: NEARBY_KEYWORDS
};
const ASCII_RE = /^[\x00-\x7F]+$/;
function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");
}
function matchKeyword(haystackLower, kwLower) {
  if (ASCII_RE.test(kwLower) && !kwLower.includes(" ")) {
    return new RegExp(`(^|[^a-z0-9])${escapeRe(kwLower)}([^a-z0-9]|$)`).test(haystackLower);
  }
  return haystackLower.includes(kwLower);
}
function matchedKeywords(haystack, needles) {
  const hits = [];
  for (const n of needles) {
    if (matchKeyword(haystack, n.toLowerCase()))
      hits.push(n);
  }
  const lower = hits.map((h) => h.toLowerCase());
  return hits.filter((h, i) => {
    const hl = lower[i];
    return !lower.some((other, j) => j !== i && other.length > hl.length && other.includes(hl));
  });
}
export function route(input) {
  const blob = (input.caption ?? "").toLowerCase();
  const scores = new Map;
  for (const corpus of PRIORITY) {
    const hits = matchedKeywords(blob, KEYWORDS[corpus]);
    if (hits.length)
      scores.set(corpus, hits);
  }
  const matched = [...scores.keys()];
  if (matched.length === 0) {
    return { corpus: null, confidence: 0.3, reasons: ["no keyword matched"] };
  }
  if (matched.length === 1) {
    const corpus = matched[0];
    return {
      corpus,
      confidence: 0.95,
      reasons: [`matched ${corpus}: ${scores.get(corpus).join(", ")}`]
    };
  }
  const ranked = matched.slice().sort((a, b) => {
    const sa = scores.get(a).length, sb = scores.get(b).length;
    if (sb !== sa)
      return sb - sa;
    return PRIORITY.indexOf(a) - PRIORITY.indexOf(b);
  });
  const winner = ranked[0];
  const runnerUp = ranked[1];
  const total = matched.reduce((sum, c) => sum + scores.get(c).length, 0);
  const winnerNorm = scores.get(winner).length / total;
  const runnerNorm = scores.get(runnerUp).length / total;
  const tied = winnerNorm - runnerNorm < TIE_THRESHOLD;
  const reasons = matched.map((c) => `matched ${c}: ${scores.get(c).join(", ")}`);
  reasons.push(`winner ${winner} (score ${scores.get(winner).length})${tied ? ` ~ tie with ${runnerUp}` : ""}`);
  return {
    corpus: winner,
    confidence: 0.7,
    reasons,
    ...tied ? { tied_with: runnerUp } : {}
  };
}
