// GENERATED by skills/_lib/transpile-browser-modules.ts from the matching
// .ts in skills/_lib — DO NOT EDIT. Edit the .ts source + re-run the
// transpile (any scaffold/ingest does it). Single-source: the CLI runs the
// .ts, the browser runs this type-erased mirror (eng-review D1).
export function buildVenueEntry(to, f) {
  const generic = {
    id: f.id,
    name_zh: f.name_zh || "(unnamed)",
    day_keys: f.day_keys || [],
    source_url: f.source_url || "",
    source_platform: f.source_platform || "manual",
    extraction_method: f.extraction_method || "manual",
    why_picked: f.why_picked || "",
    maps_query: f.maps_query || "",
    address: f.address || "",
    hours: f.hours || "",
    price: f.price || "",
    last_verified: f.last_verified
  };
  if (to !== "food")
    return generic;
  return {
    id: generic.id,
    name_zh: generic.name_zh,
    name_jp_or_local: f.name_jp_or_local || "",
    day_keys: generic.day_keys,
    anchor: f.anchor || "",
    category: f.category || "restaurant",
    kid_friendly: !!f.kid_friendly,
    source_url: generic.source_url,
    source_platform: generic.source_platform,
    extraction_method: generic.extraction_method,
    why_picked: generic.why_picked,
    backup_fit: f.backup_fit || "",
    address: generic.address,
    hours: generic.hours,
    price: generic.price,
    maps_query: generic.maps_query,
    last_verified: generic.last_verified
  };
}
